### ISSUE TITLE
AMG Workspace Setup with L1 Constructs

### ISSUE THREAD

**Issue by elamaran11** [aws-observability/cdk-aws-observability-accelerator#103]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
AMG Workspace setup with L1 Constructs to have parity with [Terraform](https://aws-observability.github.io/terraform-aws-observability-accelerator/helpers/managed-grafana/).

**Describe alternatives you've considered**

**Additional context**

**Comment by nrajb** [comment]
Quick update: I have picked this up and currently working on this
