### ISSUE TITLE
Open Source EKS on Fargate Monitoring

### ISSUE THREAD

**Issue by elamaran11** [aws-observability/cdk-aws-observability-accelerator#51]
**Is your feature request related to a problem? Please describe.**
Fargate Monitoring for EKS

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ratnopamc** [comment]
I can take this one.

**Comment by elamaran11** [comment]
@ratnopamc Any updates on this issue

**Comment by ratnopamc** [comment]
dependent on https://github.com/aws-quickstart/cdk-eks-blueprints/pull/817
