### ISSUE TITLE
Reorganize doc structure

### ISSUE THREAD

**Issue by lewinkedrs** [aws-observability/cdk-aws-observability-accelerator#55]
**Is your feature request related to a problem? Please describe.**
The current doc structure places all images into a single image directory. This will become difficult to manage at scale.

**Describe the solution you'd like**
Each markdown page will be a folder that contains the markdown along with all associated images that belong in that post. 

**Describe alternatives you've considered**
none

**Additional context**
This will allow for a better organization and naming convention then dumping all images into single directory.

**Comment by elamaran11** [comment]
@lewinkedrs Any updates on this issue.

**Comment by lewinkedrs** [comment]
Upon further review many of the pages share images so I do not think reorganizing to a folder per post is the right move here. Having images directories at the root level and the pattern level is the right move and that is what we already have. Let's close this issue.
