### ISSUE TITLE
AWS Native EKS on Fargate Monitoring

### ISSUE THREAD

**Issue by elamaran11** [aws-observability/cdk-aws-observability-accelerator#57]
**Is your feature request related to a problem? Please describe.**
AWS Native Fargate Monitoring for EKS

**Describe the solution you'd like**
AWS Native Fargate Monitoring for EKS

**Describe alternatives you've considered**

**Additional context**

**Comment by Howlla** [comment]
Adding a fargate profile to existing cluster is currently not supported as discussed here https://github.com/aws/aws-cdk/issues/13153

We can use cfnFargateProfile but that will be overwritten when aws-config is modified due to this open bug  https://github.com/aws/aws-cdk/issues/19218

**Comment by elamaran11** [comment]
This is completed. Closing this ticket.
