### ISSUE TITLE
Single New EKS Cluster Open Source Observability Accelerator pattern does not show all metrics in Grafana

### ISSUE THREAD

**Issue by freschri** [aws-observability/cdk-aws-observability-accelerator#64]
**Describe the bug**
E.g. CPU utilisation in  dashboard Kubernetes / Compute Resources / Cluster displays "No Data" (there are many others)
Reason: those panels rely on rules. The code to configure Rules in AMP is missing

**Comment by elamaran11** [comment]
This is working now. Closing this PR.
