### ISSUE TITLE
Single New EKS Cluster Open Source Observability Accelerator pattern feature to alert with AMP

### ISSUE THREAD

**Issue by elamaran11** [aws-observability/cdk-aws-observability-accelerator#67]
**Is your feature request related to a problem? Please describe.**
We need to creating [alerting rules ](https://github.com/aws-observability/terraform-aws-observability-accelerator/blob/main/modules/eks-monitoring/rules.tf) via GitOps.

**Describe the solution you'd like**
We need to creating [alerting rules ](https://github.com/aws-observability/terraform-aws-observability-accelerator/blob/main/modules/eks-monitoring/rules.tf) via GitOps.

**Describe alternatives you've considered**
We need to creating [alerting rules ](https://github.com/aws-observability/terraform-aws-observability-accelerator/blob/main/modules/eks-monitoring/rules.tf) via GitOps.

**Additional context**
We need to creating [alerting rules ](https://github.com/aws-observability/terraform-aws-observability-accelerator/blob/main/modules/eks-monitoring/rules.tf) via GitOps.

**Comment by freschri** [comment]
@elamaran11 alerting rules are created with PR 76; please check if ok

**Comment by elamaran11** [comment]
This is working now. Closing this PR.
