### ISSUE TITLE
Rename `<Pattern-Name>Construct` classes or create real constructs

### ISSUE THREAD

**Issue by matt9ucci** [aws-observability/cdk-aws-observability-accelerator#77]
**Is your feature request related to a problem? Please describe.**
Construct classes should extend the [Construct base class](https://docs.aws.amazon.com/cdk/api/v2/docs/constructs.Construct.html) in the constructs package. But `<Pattern-Name>Construct` classes do not (e.g. `SingleNewEksClusterAWSNativeobservabilityConstruct`).

**Describe the solution you'd like**
Remove `Construct` suffix  from `<Pattern-Name>Construct`.
Because these are not constructs in the context of CDK.

Not recommended to rename `<Pattern-Name>Construct` `<Pattern-Name>Pattern`.
The `Pattern` suffix will be confused with L3 _pattern_ constructs.

**Describe alternatives you've considered**
To create real constructs, make `<Pattern-Name>Construct` classes extend the Construct base class.

**Comment by shapirov103** [comment]
@matt9ucci  your logic makes sense. The current state is consistent with the patterns repo for CDK EKS Blueprints [here](https://github.com/aws-samples/cdk-eks-blueprints-patterns) so any changes will need to be applied to both. 
The confusion stems from the fact that Construct and Pattern are overloaded terms from the CDK vocabulary (which happens to be the underlying dependency). In the context of blueprints, construct and pattern literally mean blueprint construct and blueprint patterns - which is different from CDK. 
However, to avoid confusion it is reasonable to refactor once we come up with a consistent naming.

**Comment by matt9ucci** [comment]
@shapirov103 I understand the vocabulary conflicts between CDK and blueprints.

> The confusion stems from the fact that Construct and Pattern are overloaded terms from the CDK vocabulary

I agree. Construct and Pattern are the meaningful keywords of CDK, but they are commonly used in other areas.

> renaming Construct to Blueprint

LGTM 👍

**Comment by elamaran11** [comment]
@matt9ucci This is issue is fixed and closed, please reach back if you have new issues.
